FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG BACKEND_API_URL
ARG SUPABASE_URL
ARG SUPABASE_PUBLISHABLE_KEY
ARG GOOGLE_OAUTH_CLIENT_ID

ENV BACKEND_API_URL=$BACKEND_API_URL
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY
ENV GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]