spring:
  config:
    import: optional:file:.env[properties]

  application:
    name: backend

  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info